### ISSUE TITLE
[Sobre] Transparência

### ISSUE THREAD

**Issue by biribas** [softeam-org/icose-web#37]
Remover PDFs e colocar na descrição o seguinte texto:

TRANSPARÊNCIA é um dos valores do ICOSE. Acreditamos que prestações de contas claras e acessíveis contribuem para a  construção de relações duradouras baseadas na confiança e credibilidade.

Não basta ser honesto, temos que mostrar que somos honestos!

Demonstrativos financeiros e de atividades serão postados aqui.

**Comment by DanielSenaDev** [comment]
Os anexos não vão estar dentro da pasta do projeto, eles estarão em uma pasta do Google Drive.

- Atualizar codigo para o componente ter uma variavel de "name" e "url"
- Remover pasta data/transparency
- Ajustar o restante do codigo
